### ISSUE TITLE
Bug: Tuples as Parameters

### ISSUE THREAD

**Issue by mfwass** [zrax/pycdc#152] opened 2018-03-05 08:18 UTC
Using tuples as parameters is current not supported/functional in the decompiler.  I have tested this using Python 2.7 and Python 2.4, both of which yield the same result.  Original source code caused a syntax error when testing on Python 3.6, so this appears to have since been removed/deprecated.

Original source code:
```
def test((a, b, c)):
    print (a, b)

test((1,2,3))
```
Decompiled source code:
```
def test(.0):
    (a, b, c) = .0
    print (a, b)

test((1, 2, 3))
```

**Comment by rocky** [comment] 2018-04-22 08:56
@mfwass If it's not clear, what's going on is that what pycdc reports shows a little how that code gets transformed and seen by the Python interpreter. But of course `.0` is not a valid parameter name. 

I checked these examples against both [uncompyle6](https://pypi.org/p/uncompyle6) and the older not-very-well-maintained uncompyle2 and both of these work properly.

**Comment by zrax** [comment] 2019-10-10 20:24
Duplicate of #9.

**Closed by zrax** 2019-10-10 20:24 UTC
Labels: duplicate
