### ISSUE TITLE
Unsupported opcode: GEN_START

### ISSUE THREAD

**Issue by DanielTOPP** [zrax/pycdc#318] opened 2023-02-11 13:03 UTC
I am getting the erorr "Unsupported opcode: GEN_START" did i did something wrong??

**Comment by TheHellTower** [comment] 2023-02-26 19:25
> I am getting the erorr "Unsupported opcode: GEN_START" did i did something wrong??

Hello, can you send a sample ?

**Comment by TheHellTower** [comment] 2023-06-02 00:41
> I am getting the erorr "Unsupported opcode: GEN_START" did i did something wrong??

Hello, could you link a SAMPLE script that has this ? Not a actual script/program.

**Comment by EastArctica** [comment] 2023-10-18 19:44
According to the python documentation, `GEN_START` "Marks start of generator, including async, or coroutine and handles sending values to a newly created generator or coroutine."

Here's one example script that will trigger it:
```py
def gen():
    yield 0
```

which results in this:
```
# Source Generated with Decompyle++
# File: test.cpython-310.pyc (Python 3.10)


def gen():
Unsupported opcode: GEN_START
    pass
# WARNING: Decompyle incomplete
```

Note: #329 is a duplicate of this

**Comment by TheHellTower** [comment] 2023-10-18 20:33
> According to the python documentation, `GEN_START` "Marks start of generator, including async, or coroutine and handles sending values to a newly created generator or coroutine."
> 
> Here's one example script that will trigger it:
> 
> ```python
> def gen():
>     yield 0
> ```
> 
> which results in this:
> 
> ```
> # Source Generated with Decompyle++
> # File: test.cpython-310.pyc (Python 3.10)
> 
> 
> def gen():
> Unsupported opcode: GEN_START
>     pass
> # WARNING: Decompyle incomplete
> ```
> 
> Note: #329 is a duplicate of this

Hello,

Thanks for this !

[`GEN_START`](https://docs.python.org/3.10/library/dis.html#opcode-GEN_START) has 3 possible cases, would you mind trying to make a sample that generate all these cases ?
The samples doesn't need to run only to compile.

Also to verify those cases exist you can use pycdas next to [`GEN_START`](https://docs.python.org/3.10/library/dis.html#opcode-GEN_START) you will see the number ! :)

Best Regards.

**Comment by TheHellTower** [comment] 2023-10-18 21:45
> > Hello,
> > Thanks for this !
> > [`GEN_START`](https://docs.python.org/3.10/library/dis.html#opcode-GEN_START) has 3 possible cases, would you mind trying to make a sample that generate all these cases ? The samples doesn't need to run only to compile.
> > Also to verify those cases exist you can use pycdas next to [`GEN_START`](https://docs.python.org/3.10/library/dis.html#opcode-GEN_START) you will see the number ! :)
> > Best Regards.
> 
> Thanks for getting back to me so quickly. Below is a script that generates all 3 variants of the `GEN_START` opcode on `python 3.10.11`
> 
> ```python
> def a():
>     yield 0
> 
> async def b():
>     pass
> 
> async def c():
>     yield 0
> ```

Thank you ! I will try to fix this in the next 24 hours your issue will be mentioned in the Pull Request as soon as it's opened to propose a fix !

**Closed** 2023-10-20 20:42 UTC
