### ISSUE TITLE
Unsupported opcode: BINARY_OP

### ISSUE THREAD

**Issue by KOLANICH** [zrax/pycdc#333] opened 2023-03-26 18:59 UTC

**Comment by Remi-Avec-Un-I** [comment] 2023-03-26 20:17
To reproduce in python 3.11:
```
import dis

def add(a, b):
    return a + b

dis.dis(add)
```
Output : 
```
  3           0 RESUME                   0

  4           2 LOAD_FAST                0 (a)
              4 LOAD_FAST                1 (b)
              6 BINARY_OP                0 (+)
             10 RETURN_VALUE
```

**Comment by TheHellTower** [comment] 2023-05-29 04:16
> To reproduce in python 3.11:
> 
> ```
> import dis
> 
> def add(a, b):
>     return a + b
> 
> dis.dis(add)
> ```
> 
> Output :
> 
> ```
>   3           0 RESUME                   0
> 
>   4           2 LOAD_FAST                0 (a)
>               4 LOAD_FAST                1 (b)
>               6 BINARY_OP                0 (+)
>              10 RETURN_VALUE
> ```

Hey, I'm unable to reproduce this.

Could you tell me which version of Python are you using ?

![cmd_AqTbhT4eJp](https://github.com/zrax/pycdc/assets/119943599/b1035bbd-bd51-40f1-a60e-b012beb7d5f2)

**Comment by TheHellTower** [comment] 2023-05-29 04:47
@KOLANICH it should be merged soon !

**Comment by TheHellTower** [comment] 2023-05-29 06:42
It will need a lot more work I have some time before finishing this one !😄
![image](https://github.com/zrax/pycdc/assets/119943599/22d3935d-b3c4-46db-ba58-1ace61fa4f19)

**Closed** 2023-06-01 20:21 UTC

**Comment by KOLANICH** [comment] 2023-06-01 20:53
Thanks!
