### ISSUE TITLE
Python 1.5 tuple paremeters slightly incorrect. 

### ISSUE THREAD

**Issue by rocky** [zrax/pycdc#95] opened 2016-10-12 10:04 UTC
tests/15_tuple_params.pyc decompilation starts out with: 

```
# Source Generated with Decompyle++
# File: 15_tuple_params.pyc (Python 1.5)


def A(a, b, .4, c):
    (x, y, z) = .4
```

which is probably syntactically incorrect. The source code is 

```
def A(a,b,(x,y,z),c):
    pass
```

uncompyle/decompyle versions e.g. uncompyle6 (in github) handle this by looking for parameters with names that start  with `.` and then by modifying the generated AST to remove the assignment statement.

**Comment by zrax** [comment] 2019-10-10 20:33
Duplicate of #9.

**Closed by zrax** 2019-10-10 20:33 UTC
Labels: duplicate
