### ISSUE TITLE
Python3.11.2 Unsupported opcode: JUMP_BACKWARD

### ISSUE THREAD

**Issue by iveteran** [zrax/pycdc#500] opened 2024-07-20 03:41 UTC
$ ~/tools/pycdc/build/pycdc dump_filing_file_to_database.cpython-311.pyc
   ......
class Myclass:
   ...... 
    def process_filing_directories(self):
Unsupported opcode: JUMP_BACKWARD
        filings_dir = '{}/cik_*'.format(self.filing_files_dir)
    # WARNING: Decompyle incomplete

------------------------------
$ uname -a
Linux mwx001 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux

$ gcc -v
gcc version 12.2.0 (Debian 12.2.0-14)

$ python3 -V
Python 3.11.2

$ git log 
commit 6ad3ceb67ec150cc50b7a8dc796ac495b857f6db (HEAD -> master, origin/master, origin/HEAD)
| Author: easyz <130207156+ddouworld@users.noreply.github.com>
| Date:   Mon Jun 24 02:59:30 2024 +0800
......

**Comment by greenozon** [comment] 2024-07-20 05:00
There are some [PRs ](https://github.com/zrax/pycdc/pulls)pending,
find what is missed and try to build your personal binaries to play with

**Comment by zrax** [comment] 2024-08-04 19:11
Duplicate of #452

**Closed by zrax** 2024-08-04 19:11 UTC
