### ISSUE TITLE
Fix it please please sir

### ISSUE THREAD

**Issue by TechQaiser** [zrax/pycdc#214] opened 2021-11-04 20:07 UTC
![IMG-20211105-WA0010](https://user-images.githubusercontent.com/69212320/140411756-af52686f-95cc-4cc7-a0f9-3da373b6e662.jpg)

Why Pycdc Why Not Installing please Bro Update it fastly 😟

**Comment by zrax** [comment] 2021-11-04 22:19
Duplicate of #212

**Closed by zrax** 2021-11-04 22:19 UTC
