### ISSUE TITLE
Unsupported opcode: RETURN_GENERATOR

### ISSUE THREAD

**Issue by 3bd2lra7man** [zrax/pycdc#465] opened 2024-03-02 19:17 UTC
Please add this opcode to your tool, RETURN_GENERATOR in python 3.11

**Comment by TiZCrocodile** [comment] 2024-03-02 22:36
duplicate of #452

**Comment by 3bd2lra7man** [comment] 2024-03-02 23:48
> duplicate of #452

How can I help in adding these codes? Is it something complicated, and what knowledge do I need to contribute to this?

**Closed** 2024-03-03 00:05 UTC

**Comment by TiZCrocodile** [comment] 2024-03-03 02:50
> > duplicate of #452
> 
> How can I help in adding these codes? Is it something complicated, and what knowledge do I need to contribute to this?

its sometimes complicated and sometimes not, you have to understand how cpython implements this bytecode, maybe read the docs about this opcode, then try to understand this project and how it works, `ASTree.cpp` is the file that handles support for the opcodes, there is a switch case for every opcode, you can add support for this opcode after you understand what is does, good luck!
